/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Contact = {
    'active' : {
      'id' : bigint,
      'name' : string,
      'email' : string,
      'company' : string,
      'notes' : Array<string>,
      'phone' : string,
    }
  } |
  {
    'lead' : {
      'id' : bigint,
      'name' : string,
      'email' : string,
      'company' : string,
      'stage' : Stage,
      'notes' : Array<string>,
      'phone' : string,
    }
  } |
  {
    'inactive' : {
      'id' : bigint,
      'name' : string,
      'email' : string,
      'company' : string,
      'notes' : Array<string>,
      'phone' : string,
    }
  };
export type Stage = { 'New' : null } |
  { 'Contacted' : null } |
  { 'Qualified' : null } |
  { 'Proposal' : null } |
  { 'ClosedWon' : null } |
  { 'ClosedLost' : null };
export interface _SERVICE {
  'addContact' : ActorMethod<[string, string, string, string], bigint>,
  'addNote' : ActorMethod<[bigint, string], boolean>,
  'convertLeadToActive' : ActorMethod<[bigint], boolean>,
  'convertStage' : ActorMethod<[bigint, Stage], boolean>,
  'countContactsByStage' : ActorMethod<[Stage], bigint>,
  'deleteContact' : ActorMethod<[bigint], boolean>,
  'getActiveContacts' : ActorMethod<[], Array<Contact>>,
  'getAllContacts' : ActorMethod<[], Array<Contact>>,
  'getContact' : ActorMethod<[bigint], [] | [Contact]>,
  'getContactCount' : ActorMethod<[], bigint>,
  'getContactsByStage' : ActorMethod<[Stage], Array<Contact>>,
  'getInactiveContacts' : ActorMethod<[], Array<Contact>>,
  'getNextId' : ActorMethod<[], bigint>,
  'getStats' : ActorMethod<
    [],
    {
      'closedWon' : bigint,
      'totalContacts' : bigint,
      'newLeads' : bigint,
      'proposal' : bigint,
      'contacted' : bigint,
      'qualified' : bigint,
      'closedLost' : bigint,
    }
  >,
  'setContactInactive' : ActorMethod<[bigint], boolean>,
  'updateContact' : ActorMethod<[bigint, Contact], boolean>,
  'updateContactStage' : ActorMethod<[bigint, Stage], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];