/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Stage = IDL.Variant({
  'New' : IDL.Null,
  'Contacted' : IDL.Null,
  'Qualified' : IDL.Null,
  'Proposal' : IDL.Null,
  'ClosedWon' : IDL.Null,
  'ClosedLost' : IDL.Null,
});
export const Contact = IDL.Variant({
  'active' : IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'notes' : IDL.Vec(IDL.Text),
    'phone' : IDL.Text,
  }),
  'lead' : IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'stage' : Stage,
    'notes' : IDL.Vec(IDL.Text),
    'phone' : IDL.Text,
  }),
  'inactive' : IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'notes' : IDL.Vec(IDL.Text),
    'phone' : IDL.Text,
  }),
});

export const idlService = IDL.Service({
  'addContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addNote' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'convertLeadToActive' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'convertStage' : IDL.Func([IDL.Nat, Stage], [IDL.Bool], []),
  'countContactsByStage' : IDL.Func([Stage], [IDL.Nat], ['query']),
  'deleteContact' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getActiveContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getContact' : IDL.Func([IDL.Nat], [IDL.Opt(Contact)], ['query']),
  'getContactCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getContactsByStage' : IDL.Func([Stage], [IDL.Vec(Contact)], ['query']),
  'getInactiveContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getNextId' : IDL.Func([], [IDL.Nat], ['query']),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'closedWon' : IDL.Nat,
          'totalContacts' : IDL.Nat,
          'newLeads' : IDL.Nat,
          'proposal' : IDL.Nat,
          'contacted' : IDL.Nat,
          'qualified' : IDL.Nat,
          'closedLost' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'setContactInactive' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateContact' : IDL.Func([IDL.Nat, Contact], [IDL.Bool], []),
  'updateContactStage' : IDL.Func([IDL.Nat, Stage], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Stage = IDL.Variant({
    'New' : IDL.Null,
    'Contacted' : IDL.Null,
    'Qualified' : IDL.Null,
    'Proposal' : IDL.Null,
    'ClosedWon' : IDL.Null,
    'ClosedLost' : IDL.Null,
  });
  const Contact = IDL.Variant({
    'active' : IDL.Record({
      'id' : IDL.Nat,
      'name' : IDL.Text,
      'email' : IDL.Text,
      'company' : IDL.Text,
      'notes' : IDL.Vec(IDL.Text),
      'phone' : IDL.Text,
    }),
    'lead' : IDL.Record({
      'id' : IDL.Nat,
      'name' : IDL.Text,
      'email' : IDL.Text,
      'company' : IDL.Text,
      'stage' : Stage,
      'notes' : IDL.Vec(IDL.Text),
      'phone' : IDL.Text,
    }),
    'inactive' : IDL.Record({
      'id' : IDL.Nat,
      'name' : IDL.Text,
      'email' : IDL.Text,
      'company' : IDL.Text,
      'notes' : IDL.Vec(IDL.Text),
      'phone' : IDL.Text,
    }),
  });
  
  return IDL.Service({
    'addContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addNote' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
    'convertLeadToActive' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'convertStage' : IDL.Func([IDL.Nat, Stage], [IDL.Bool], []),
    'countContactsByStage' : IDL.Func([Stage], [IDL.Nat], ['query']),
    'deleteContact' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getActiveContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getContact' : IDL.Func([IDL.Nat], [IDL.Opt(Contact)], ['query']),
    'getContactCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getContactsByStage' : IDL.Func([Stage], [IDL.Vec(Contact)], ['query']),
    'getInactiveContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getNextId' : IDL.Func([], [IDL.Nat], ['query']),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'closedWon' : IDL.Nat,
            'totalContacts' : IDL.Nat,
            'newLeads' : IDL.Nat,
            'proposal' : IDL.Nat,
            'contacted' : IDL.Nat,
            'qualified' : IDL.Nat,
            'closedLost' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'setContactInactive' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateContact' : IDL.Func([IDL.Nat, Contact], [IDL.Bool], []),
    'updateContactStage' : IDL.Func([IDL.Nat, Stage], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };