/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Contact = {
    __kind__: "active";
    active: {
        id: bigint;
        name: string;
        email: string;
        company: string;
        notes: Array<string>;
        phone: string;
    };
} | {
    __kind__: "lead";
    lead: {
        id: bigint;
        name: string;
        email: string;
        company: string;
        stage: Stage;
        notes: Array<string>;
        phone: string;
    };
} | {
    __kind__: "inactive";
    inactive: {
        id: bigint;
        name: string;
        email: string;
        company: string;
        notes: Array<string>;
        phone: string;
    };
};
export enum Stage {
    New = "New",
    Contacted = "Contacted",
    Qualified = "Qualified",
    Proposal = "Proposal",
    ClosedWon = "ClosedWon",
    ClosedLost = "ClosedLost"
}
export interface backendInterface {
    addContact(name: string, email: string, phone: string, company: string): Promise<bigint>;
    addNote(id: bigint, note: string): Promise<boolean>;
    convertLeadToActive(id: bigint): Promise<boolean>;
    convertStage(id: bigint, newStage: Stage): Promise<boolean>;
    countContactsByStage(stage: Stage): Promise<bigint>;
    deleteContact(id: bigint): Promise<boolean>;
    getActiveContacts(): Promise<Array<Contact>>;
    getAllContacts(): Promise<Array<Contact>>;
    getContact(id: bigint): Promise<Contact | null>;
    getContactCount(): Promise<bigint>;
    getContactsByStage(stage: Stage): Promise<Array<Contact>>;
    getInactiveContacts(): Promise<Array<Contact>>;
    getNextId(): Promise<bigint>;
    getStats(): Promise<{
        closedWon: bigint;
        totalContacts: bigint;
        newLeads: bigint;
        proposal: bigint;
        contacted: bigint;
        qualified: bigint;
        closedLost: bigint;
    }>;
    setContactInactive(id: bigint): Promise<boolean>;
    updateContact(id: bigint, contact: Contact): Promise<boolean>;
    updateContactStage(id: bigint, stage: Stage): Promise<boolean>;
}
import type { Contact as _Contact, Stage as _Stage } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addContact(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addContact(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContact(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addNote(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNote(arg0, arg1);
            return result;
        }
    }
    async convertLeadToActive(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.convertLeadToActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.convertLeadToActive(arg0);
            return result;
        }
    }
    async convertStage(arg0: bigint, arg1: Stage): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.convertStage(arg0, to_candid_Stage_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.convertStage(arg0, to_candid_Stage_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async countContactsByStage(arg0: Stage): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.countContactsByStage(to_candid_Stage_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.countContactsByStage(to_candid_Stage_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteContact(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContact(arg0);
            return result;
        }
    }
    async getActiveContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveContacts();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveContacts();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContacts();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContacts();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContact(arg0: bigint): Promise<Contact | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContact(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContact(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactCount();
            return result;
        }
    }
    async getContactsByStage(arg0: Stage): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactsByStage(to_candid_Stage_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactsByStage(to_candid_Stage_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInactiveContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInactiveContacts();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInactiveContacts();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNextId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextId();
            return result;
        }
    }
    async getStats(): Promise<{
        closedWon: bigint;
        totalContacts: bigint;
        newLeads: bigint;
        proposal: bigint;
        contacted: bigint;
        qualified: bigint;
        closedLost: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async setContactInactive(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setContactInactive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setContactInactive(arg0);
            return result;
        }
    }
    async updateContact(arg0: bigint, arg1: Contact): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContact(arg0, to_candid_Contact_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContact(arg0, to_candid_Contact_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateContactStage(arg0: bigint, arg1: Stage): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContactStage(arg0, to_candid_Stage_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContactStage(arg0, to_candid_Stage_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Contact_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contact): Contact {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Stage_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Stage): Stage {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Contact]): Contact | null {
    return value.length === 0 ? null : from_candid_Contact_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    email: string;
    company: string;
    stage: _Stage;
    notes: Array<string>;
    phone: string;
}): {
    id: bigint;
    name: string;
    email: string;
    company: string;
    stage: Stage;
    notes: Array<string>;
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        email: value.email,
        company: value.company,
        stage: from_candid_Stage_n7(_uploadFile, _downloadFile, value.stage),
        notes: value.notes,
        phone: value.phone
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: {
        id: bigint;
        name: string;
        email: string;
        company: string;
        notes: Array<string>;
        phone: string;
    };
} | {
    lead: {
        id: bigint;
        name: string;
        email: string;
        company: string;
        stage: _Stage;
        notes: Array<string>;
        phone: string;
    };
} | {
    inactive: {
        id: bigint;
        name: string;
        email: string;
        company: string;
        notes: Array<string>;
        phone: string;
    };
}): {
    __kind__: "active";
    active: {
        id: bigint;
        name: string;
        email: string;
        company: string;
        notes: Array<string>;
        phone: string;
    };
} | {
    __kind__: "lead";
    lead: {
        id: bigint;
        name: string;
        email: string;
        company: string;
        stage: Stage;
        notes: Array<string>;
        phone: string;
    };
} | {
    __kind__: "inactive";
    inactive: {
        id: bigint;
        name: string;
        email: string;
        company: string;
        notes: Array<string>;
        phone: string;
    };
} {
    return "active" in value ? {
        __kind__: "active",
        active: value.active
    } : "lead" in value ? {
        __kind__: "lead",
        lead: from_candid_record_n6(_uploadFile, _downloadFile, value.lead)
    } : "inactive" in value ? {
        __kind__: "inactive",
        inactive: value.inactive
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    New: null;
} | {
    Contacted: null;
} | {
    Qualified: null;
} | {
    Proposal: null;
} | {
    ClosedWon: null;
} | {
    ClosedLost: null;
}): Stage {
    return "New" in value ? Stage.New : "Contacted" in value ? Stage.Contacted : "Qualified" in value ? Stage.Qualified : "Proposal" in value ? Stage.Proposal : "ClosedWon" in value ? Stage.ClosedWon : "ClosedLost" in value ? Stage.ClosedLost : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Contact>): Array<Contact> {
    return value.map((x)=>from_candid_Contact_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Contact_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Contact): _Contact {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Stage_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Stage): _Stage {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    email: string;
    company: string;
    stage: Stage;
    notes: Array<string>;
    phone: string;
}): {
    id: bigint;
    name: string;
    email: string;
    company: string;
    stage: _Stage;
    notes: Array<string>;
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        email: value.email,
        company: value.company,
        stage: to_candid_Stage_n1(_uploadFile, _downloadFile, value.stage),
        notes: value.notes,
        phone: value.phone
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "active";
    active: {
        id: bigint;
        name: string;
        email: string;
        company: string;
        notes: Array<string>;
        phone: string;
    };
} | {
    __kind__: "lead";
    lead: {
        id: bigint;
        name: string;
        email: string;
        company: string;
        stage: Stage;
        notes: Array<string>;
        phone: string;
    };
} | {
    __kind__: "inactive";
    inactive: {
        id: bigint;
        name: string;
        email: string;
        company: string;
        notes: Array<string>;
        phone: string;
    };
}): {
    active: {
        id: bigint;
        name: string;
        email: string;
        company: string;
        notes: Array<string>;
        phone: string;
    };
} | {
    lead: {
        id: bigint;
        name: string;
        email: string;
        company: string;
        stage: _Stage;
        notes: Array<string>;
        phone: string;
    };
} | {
    inactive: {
        id: bigint;
        name: string;
        email: string;
        company: string;
        notes: Array<string>;
        phone: string;
    };
} {
    return value.__kind__ === "active" ? {
        active: value.active
    } : value.__kind__ === "lead" ? {
        lead: to_candid_record_n12(_uploadFile, _downloadFile, value.lead)
    } : value.__kind__ === "inactive" ? {
        inactive: value.inactive
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Stage): {
    New: null;
} | {
    Contacted: null;
} | {
    Qualified: null;
} | {
    Proposal: null;
} | {
    ClosedWon: null;
} | {
    ClosedLost: null;
} {
    return value == Stage.New ? {
        New: null
    } : value == Stage.Contacted ? {
        Contacted: null
    } : value == Stage.Qualified ? {
        Qualified: null
    } : value == Stage.Proposal ? {
        Proposal: null
    } : value == Stage.ClosedWon ? {
        ClosedWon: null
    } : value == Stage.ClosedLost ? {
        ClosedLost: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
